<?php
?>
<article>
    <div class="page-header">
        <h1>Modify page content</h1>
    </div>

    <div class="row-fluid">
        <div class="editor">
            <?= $this->form()->openTag($form)?>
            <?= $this->formRow($form->get('content'))?>
            <?= $this->formRow($form->get('submit'))?>
            <?= $this->form()->closeTag($form)?>
        </div>
    </div>

</article>